BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        TextInput:
            text: "34"
            size_hint_x: 0.8
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.2
            Button:
                text: "Up"
            Button:
                text: "Down"
    Button:
        text: "Convert m to km"
    Label:
        text: "54.61756"
        color: (0.95, 0.95, 0.03, 1)